import PDFDocument from 'pdfkit';
import { Ticket, TicketMessage, TicketNote } from '../types';

const COLORS = {
  ink: '#1e1f22',
  muted: '#6d6f78',
  accent: '#5865f2',
  green: '#3ba55c',
  amber: '#b9770e',
  line: '#e3e5e8',
};

function fmt(iso: string): string {
  return new Date(iso).toLocaleString('en-GB', {
    year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

export function generateTranscriptPdf(params: {
  ticket: Ticket;
  messages: TicketMessage[];
  notes?: TicketNote[];
  openedByTag: string;
  agentTag: string | null;
  guildName: string;
  includeInternal?: boolean;
}): Promise<Buffer> {
  const { ticket, messages, openedByTag, agentTag, guildName } = params;
  const includeInternal = params.includeInternal !== false;
  const notes = includeInternal ? (params.notes ?? []) : [];

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const W = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    // ── Header
    doc.fillColor(COLORS.accent).fontSize(20).font('Helvetica-Bold')
      .text(`Ticket #${ticket.ticket_number}`, { continued: false });
    doc.fillColor(COLORS.ink).fontSize(14).font('Helvetica-Bold')
      .text(ticket.subject || '(no subject)');
    doc.moveDown(0.3);

    const meta = [
      `Status: ${ticket.status}`,
      `Opened by: ${openedByTag}`,
      agentTag ? `Agent: ${agentTag}` : null,
      `Opened: ${fmt(ticket.created_at)}`,
      ticket.closed_at ? `Closed: ${fmt(ticket.closed_at)}` : null,
      ticket.rating ? `Rating: ${ticket.rating}/5` : null,
      `Server: ${guildName}`,
    ].filter(Boolean).join('   •   ');
    doc.fontSize(9).font('Helvetica').fillColor(COLORS.muted).text(meta);
    doc.moveDown(0.5);
    doc.moveTo(doc.x, doc.y).lineTo(doc.x + W, doc.y).strokeColor(COLORS.line).lineWidth(1).stroke();
    doc.moveDown(0.7);

    const sectionLabel = (text: string, color: string) => {
      doc.moveDown(0.3);
      doc.fontSize(10).font('Helvetica-Bold').fillColor(color).text(text.toUpperCase());
      doc.moveDown(0.2);
    };

    // ── Original submission
    sectionLabel('Ticket submitted', COLORS.accent);
    doc.fontSize(10).font('Helvetica').fillColor(COLORS.ink)
      .text(ticket.description || '(no description)', { width: W });

    // ── Resolution (+ internal reason for staff)
    if (ticket.resolution || (includeInternal && ticket.close_reason)) {
      sectionLabel('Resolution', COLORS.green);
      if (ticket.resolution) doc.fontSize(10).font('Helvetica').fillColor(COLORS.ink).text(ticket.resolution, { width: W });
      if (includeInternal && ticket.close_reason) {
        doc.fontSize(9).font('Helvetica-Oblique').fillColor(COLORS.muted).text(`Internal reason: ${ticket.close_reason}`, { width: W });
      }
    }

    // ── Internal notes (staff only)
    if (notes.length > 0) {
      sectionLabel(`Internal notes (${notes.length})`, COLORS.amber);
      for (const n of notes) {
        doc.fontSize(9).font('Helvetica-Bold').fillColor(COLORS.ink)
          .text(`${n.author_tag}`, { continued: true })
          .font('Helvetica').fillColor(COLORS.muted).text(`   ${fmt(n.created_at)}`);
        doc.fontSize(10).font('Helvetica').fillColor(COLORS.ink).text(n.note, { width: W });
        doc.moveDown(0.2);
      }
    }

    // ── Conversation
    sectionLabel(messages.length ? 'Conversation' : 'Conversation (no messages recorded)', COLORS.muted);
    for (const m of messages) {
      doc.fontSize(10).font('Helvetica-Bold').fillColor(COLORS.ink)
        .text(m.username, { continued: true })
        .font('Helvetica').fontSize(8).fillColor(COLORS.muted).text(`   ${fmt(m.created_at)}`);
      if (m.content) {
        doc.fontSize(10).font('Helvetica').fillColor(COLORS.ink).text(m.content, { width: W });
      }
      for (const a of m.attachments) {
        doc.fontSize(9).font('Helvetica-Oblique').fillColor(COLORS.accent).text(`[attachment] ${a.name}`, { width: W });
      }
      doc.moveDown(0.4);
    }

    // ── Footer (in normal flow — avoids pdfkit auto-paginating into a blank page)
    doc.moveDown(1.2);
    doc.fontSize(8).font('Helvetica').fillColor(COLORS.muted)
      .text(`Generated by ZendeskBotForOO • ${new Date().toUTCString()}`, { align: 'center' });

    doc.end();
  });
}
